name: Deploy to WordPress.org

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy Plugin
    runs-on: ubuntu-latest
    steps:
      # Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Deploy to WordPress.org via SVN
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@1.4.0
        with:
          slug: betterblocks
          build-dir: ./
          assets-dir: ./assets
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}